safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: yandex2
default_width: 1024
default_ratio: 16x9
default_lang: en
default_body_class: list

presentation:
    title: Presentation Title
    service: Service name
    nda: true
    lang: ru

author:
    name: Author Name
    position: Position
    company:
        name: Yandex
        url:  http://yandex.com/

fork_url: https://github.yandex-team.ru/dima117a/jekyller
progress: true
